### ISSUE TITLE
PHP Fatal error:  Uncaught Gitlab\Exception\RuntimeException: 404 Not Found

### ISSUE THREAD

**Issue by huliuqing** [m4tthumphrey/php-gitlab-api#458]
## problem

When I build a merge request use the mr api, it give me some errors.

1. some warning
```sh
PHP Warning:  Yaf_Loader::autoload(): Failed opening script /data/web/mysite.com/releases/origin/hlq/newapp/src/application/library/Http/Client/Common/HttpMethodsClientInterface.php: No such file or directory in /data/web/mysite.com/releases/origin/hlq/newapp/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Plugin/HistoryTrait.php on line 10
PHP Warning:  Yaf_Loader::autoload(): Failed opening script /data/web/mysite.com/releases/origin/hlq/newapp/src/application/library/Symfony/Component/HttpClient/HttplugClient.php: No such file or directory in /data/web/mysite.com/releases/origin/hlq/newapp/vendor/php-http/discovery/src/ClassDiscovery.php on line 231
PHP Warning:  Yaf_Loader::autoload(): Failed opening script /data/web/mysite.com/releases/origin/hlq/newapp/src/application/library/Nyholm/Psr7/Factory/HttplugFactory.php: No such file or directory in /data/web/mysite.com/releases/origin/hlq/newapp/vendor/php-http/discovery/src/ClassDiscovery.php on line 231
PHP Warning:  Yaf_Loader::autoload(): Failed opening script /data/web/mysite.com/releases/origin/hlq/newapp/src/application/library/Nyholm/Psr7/Factory/HttplugFactory.php: No such file or directory in /data/web/mysite.com/releases/origin/hlq/newapp/vendor/php-http/discovery/src/ClassDiscovery.php on line 231
PHP Warning:  Yaf_Loader::autoload(): Failed opening script /data/web/mysite.com/releases/origin/hlq/newapp/src/application/library/Nyholm/Psr7/Factory/HttplugFactory.php: No such file or directory in /data/web/mysite.com/releases/origin/hlq/newapp/vendor/php-http/discovery/src/ClassDiscovery.php on line 231
```

2.  A fatal error
```sh
PHP Fatal error:  Uncaught Gitlab\Exception\RuntimeException: 404 Not Found in /data/web/mysite.com/releases/origin/hlq/newapp/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Plugin/GitlabExceptionThrower.php:50
Stack trace:
#0 /data/web/mysite.com/releases/origin/hlq/newapp/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): Gitlab\HttpClient\Plugin\GitlabExceptionThrower->Gitlab\HttpClient\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 /data/web/mysite.com/releases/origin/hlq/newapp/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Plugin/GitlabExceptionThrower.php(54): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure))
#2 /data/web/mysite.com/releases/origin/hlq/newapp/vendor/php-http/client-common/src/Plugin/VersionBridgePlugin.php(19): Gitlab\HttpClient\Plugin\GitlabExceptionThrower->doHandleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#3 /data/web/pre2-api-growth.qkto in /data/web/mysite.com/releases/origin/hlq/newapp/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Plugin/GitlabExceptionThrower.php on line 50
```

## What I did
I install the dependency library as the doc guide says:

```
composer require m4tthumphrey/php-gitlab-api php-http/guzzle6-adapter:^1.0
```

## more try

I have try to install earlier version like below, but not work:

```sh
composer require m4tthumphrey/php-gitlab-api:9.11 php-http/guzzle6-adapter:^1.0
```

**Comment by huliuqing** [comment]
Yet I found the anwser:

In version 9.11 it lost some required dependency library, **symfony/http-client** and **nyholm/psr7**.

If you got the same problem, and installed this libaray yet,you need remove it first and then execute  command: 

```sh
composer require m4tthumphrey/php-gitlab-api:9.11 php-http/guzzle6-adapter:^1.0 nyholm/psr7 symfony/http-client
```
