### ISSUE TITLE
Calling API for a Project that is shared with a Group fails

### ISSUE THREAD

**Issue by donkidd** [m4tthumphrey/php-gitlab-api#466]
When trying to create a Project for a group that is shared with another group, I am getting the following error.  The lib/Gitlab/Model/Group.php file is looking for a 'id' field but inside the "shared_with_group" actually has the "group_id" field instead of the "id".  

```
Undefined index: id {"exception":"[object] (ErrorException(code: 0): Undefined index: id at /var/www/apps/grok/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Model/Group.php:54)
[stacktrace]
#0 /var/www/apps/grok/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Model/Group.php(54): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/apps/g...', 54, Array)
#1 /var/www/apps/grok/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/Model/Project.php(120): Gitlab\\Model\\Group::fromArray(Object(Gitlab\\Client), Array)
```

```
"shared_with_groups": [
        {
            "group_id": 241,
            "group_name": "Group Name",
            "group_full_path": "group",
            "group_access_level": 30,
            "expires_at": null
        }
    ],
```

**Comment by m1guelpf** [comment]
PRs welcome
