### ISSUE TITLE
[Bug] Commit ID should be a string, not a int

### ISSUE THREAD

**Issue by Gounlaf** [m4tthumphrey/php-gitlab-api#574]
Hi,

With commit https://github.com/GitLabPHP/Client/commit/9292486eadc79f3ac65416afe83dcf7455a8a70d type hinting were added.

I got the exception below doing something like this (simplified):

```php
$projects = $this->gitlabClient->groups()->show($groupId);
$project = Project::fromArray($this->gitlabClient, $projects[0]);
$branches = $project->branches();
```

If I'm not wrong, commits IDs are always string.

```
Fatal error: Uncaught TypeError: Argument 2 passed to Gitlab\Model\Commit::__construct() must be of the type int or null, string given,
called in /var/www/html/vendor/m4tthumphrey/php-gitlab-api/src/Model/Commit.php on line 59 and defined in /var/www/html/vendor/m4tthumphrey/php-gitlab-api/src/Model/Commit.php:88
Stack trace: #0 /var/www/html/vendor/m4tthumphrey/php-gitlab-api/src/Model/Commit.php(59): Gitlab\Model\Commit->__construct(Object(Gitlab\Model\Project), 'fbc6ba41e98c6e2...', Object(Gitlab\Client))
#1 /var/www/html/vendor/m4tthumphrey/php-gitlab-api/src/Model/Branch.php(40): Gitlab\Model\Commit::fromArray(Object(Gitlab\Client), Object(Gitlab\Model\Project), Array)
#2 /var/www/html/vendor/m4tthumphrey/php-gitlab-api/src/Model/Project.php(463): Gitlab\Model\Branch::fromArray(Object(Gitlab\Client), Object(Gitlab\Model\Project), Array)
#3 /var/www/html/app/Controller/ApiController.php(79): Gitlab\Model\Project->branches()
#4 /var/www/html/public/index.php(45): App\Controller\ApiController->api(Object(Nyholm\Psr7\Ser in /var/www/html/vendor/m4tthumphrey/php-gitlab-api/src/Model/Commit.php on line 88
```

I will create a PR soon,

Regards,

Edit: Phpdoc for class still refer to string for id/short_id too.

**Comment by GrahamCampbell** [comment]
Fixed.
